# Generated by Django 5.0.6 on 2024-07-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(on_delete=models.SET('Unknown'), related_name='players', to='base.nation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='users', to='base.player'),
        ),
    ]
