# Generated by Django 5.0.6 on 2024-07-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_player_nationality_alter_user_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_club',
            field=models.ForeignKey(on_delete=models.SET('Unknown'), related_name='players', to='base.club'),
        ),
    ]
