# Generated by Django 5.0.6 on 2024-07-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_player_current_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='current_club',
            new_name='club',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='nationality',
            new_name='nation',
        ),
    ]
