# Generated by Django 5.0.7 on 2024-07-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
    ]
