# Generated by Django 5.0.7 on 2024-07-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_current_club_player_club_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='player',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
