# Generated by Django 5.0.7 on 2024-07-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_player_profile_picture_player_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='club',
            name='foundation_date',
        ),
        migrations.RemoveField(
            model_name='club',
            name='ground',
        ),
        migrations.RemoveField(
            model_name='club',
            name='head_coach',
        ),
        migrations.RemoveField(
            model_name='club',
            name='league',
        ),
        migrations.RemoveField(
            model_name='club',
            name='president',
        ),
        migrations.RemoveField(
            model_name='club',
            name='website',
        ),
        migrations.RemoveField(
            model_name='nation',
            name='world_ranking',
        ),
    ]
